### ISSUE TITLE
Accept optional punctuation separating words from issue numbers

### ISSUE THREAD

**Issue by PhilMiller** [DARMA-tasking/check-pr-fixes-issue#2]
Right now, a title `#1056: Do stuff` is not accepted because the regex looks for a space immediately following the issue number. 

I the the regex should be something more like `^#?\d+([:;,/&]?|\s).+$`

Similarly, in the body, `Fixes: #1056` is not accepted by the check (though it is picked up by Github) because of the `:`

**Comment by jstrzebonski** [comment]
I just wonder if `[;/&]` make sense? I mean, I can imagine 
`#1056: Do stuff`
`#1056, Do stuff`
`#1056 - Do stuff`

but not really 
`#1056& Do stuff`
or is it more like `#1055 & #965: ...` ?

**Comment by PhilMiller** [comment]
Yeah. Really, I think we should be quite a bit looser, as long as there's something that looks like an issue number separated from any other text at the beginning.

**Comment by jstrzebonski** [comment]
Sure, I can fix it tomorrow.
