### ISSUE TITLE
Check fails if PR title start with #, even though regex seems to allow it?

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/check-pr-fixes-issue#4]
In VT, when the title ends with a color `:` (or maybe it's the pound?), it seems to disallow it even though that is supposed to be allowed through the regex. Not sure what is going on there:

https://github.com/DARMA-tasking/check-pr-fixes-issue/blob/087ae36fe0f8f3838bce3e43f8a8ccd72a6d8504/tests/helpers.test.js#L27-L29

```
Run DARMA-tasking/check-pr-fixes-issue@master
  with:
    pr_branch: 1075-run-description-when-edited
    pr_title: #1075: Run PR description when edited
    pr_description: Fixes #1075
  
  The check should run when edited now! The default set is:
  
  > By default, a workflow only runs when a pull_request_target's activity type is opened, synchronize, or reopened. To trigger workflows for more activity types, use the types keyword. For more information, see "Workflow syntax for GitHub Actions."
  
  Removing the set made it not run on `edited`. This should fix the problem
##[error]PR title doesn't start with issue number
```

**Comment by lifflander** [comment]
Not sure what is going on here. Maybe you can investigate when you have some time. I made the check optional for now until we solve this problem.

**Comment by jstrzebonski** [comment]
Yeah, I've already started to look at this, this morning, but that's strange because unit tests work perfectly fine with this case. I'll try to mimic the whole situation (branch name, pr title + body) on my test repo later today and see what will happen.

**Comment by jstrzebonski** [comment]
OK, that's something funny - DARMA-tasking/vt#1029
After changing the title to `#1014: dump node...` check is failing :'- (
But that's good, that's a concrete case to work on.
